apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-traffic
  namespace: argo-gitops-car-app 
spec:
  source:
    repoURL: https://github.com/usmanfarooq317/argo-gitops-car-app
    path: k8s
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-gitops-car-app 
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true 
