apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-traffic
  namespace: argocd       # ArgoCD namespace
spec:
  project: default        # ðŸ‘ˆ REQUIRED
  source:
    repoURL: https://github.com/usmanfarooq317/argocd-gitops-car-app
    path: k8s
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-gitops-car-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
