apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-traffic
  namespace: argocd                 # ðŸ‘ˆ MUST be argocd namespace
spec:
  destination:
    namespace: argo-gitops-car-app # ðŸ‘ˆ your app namespace
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/usmanfarooq317/argo-gitops-car-app
    path: k8s
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
